// Imports from the pre-built server bundle generated by scripts/build-server.mjs.
// Vercel does NOT bundle TypeScript imports outside api/ when "type":"module"
// is set — it only transpiles this file. The _server.js bundle (underscore prefix
// = Vercel ignores it as a function entry point) is built by `npm run build`.
export { default } from "./_server.js";
